### ISSUE TITLE
Theming: Mobile-compatibility

### ISSUE THREAD

**Issue by dvenckusuchgo** [CBIIT/ccdhwebportal#15]
There are page elements not working correctly with mobile screen sizes:

- Footer
- Tables: project timeline, standards and tooling

Switching to the built-in XY-Grid will improve mobile displays

**Comment by dvenckusuchgo** [comment]
I broke apart the rather large unwieldy page.html.twig template into subtemplates.  Page.html.twig remains the master page template, but it includes the individual region templates found in the theme:templates/regions subdirectory.

Footer has been restyled to be consistent with https://datacommons.cancer.gov and improved mobile-compatibility.

**Comment by dvenckusuchgo** [comment]
The "Standards and Tooling" table was easily fixed for mobile sizes by adding, 
`table-layout:fixed;` to the embedded styling for the Drupal node.
The Project Timeline table continues to have a problem with smaller screens. Needs to be revisted.

**Comment by dvenckusuchgo** [comment]
Styles in "Project Timeline" fixed to allow for table scrolling at smaller screen sizes

**Comment by bfurner** [comment]
regarding the footer, all other instances of the footer that i've seen on NCI sites are fixed width, centered (or at least have a max-width defined).  i suspect they will have issues if ours is not comparable.  let's make ours match theirs if possible on the footer.

**Comment by dvenckusuchgo** [comment]
Matched the padding and alignment of the datacommons.cancer.gov footer

**Comment by dvenckusuchgo** [comment]
Resolving.  Open new issues under new tickets.
