### ISSUE TITLE
Upgrade & Override D8 Core Modernizr Library 

### ISSUE THREAD

**Issue by dvenckusuchgo** [CBIIT/ccdhwebportal#2]
Modernizr in Drupal 8 core is 3.3.1.  The latest version is 3.5.  
We can roll our own here, [Modernizer](https://modernizr.com/download?setclasses)

Using the exact same features as D8 core, this is our request URL
[Version 3.5](http://modernizr.com/download/?-details-inputtypes-touchevents-addtest-prefixes-setclasses-teststyles)

We will need to override the core version and add the new version to our custom subtheme.

**Comment by dvenckusuchgo** [comment]
Given the theme structure, this will require a subtheme of ccdh_foundation theme so we can add assets and customizations required for the project.  The new modernizr js library will reside with the ccdh subtheme.

**Comment by dvenckusuchgo** [comment]
We'll be using ccdh_foundation theme.  Cleanup of themes ( #4 ) is a pre-requisite for this issue

**Comment by dvenckusuchgo** [comment]
Even thought the v3.3.1 drupal/core modernizr js lib was not being loaded in the browser due to the theme override using modernizr v3.6.0, Brian noticed the original core file was still directly accessible.  This has been fixed by doing a git-diff/composer patch of the core files that get applied during "composer install".  Modernizr v3.3.1 is no more.

**Comment by bfurner** [comment]
@dvenckusuchgo i believe the minimum version that addresses the security issue is 3.11.0, so we'll need to at least be at that version to pass the security check.  thanks

**Comment by bfurner** [comment]
you have to get releases from their github [repo](https://github.com/Modernizr/Modernizr/releases) not from their website.

**Comment by dvenckusuchgo** [comment]
### How to Build Modernizer js lib ###
- Download latest release from [Github:Modernizr/Modernizr](https://github.com/Modernizr/Modernizr/releases) (zip or tar.gz) and uncompress as [release dir or something deeply meaningful]
- ```cd [release dir]; npm install```
- edit ```./lib/config-all.json``` changing ```"minify": true```, then save
- from [release_dir] run ```npm start```
- the new modernizr js file will appear as ./dist/modernizr-build.js 
- rename it:  ```mv ./dist/modernizr-build.js ./dist/modernizr.min.js```
- drop it into it's required location in your favorite project

**Comment by dvenckusuchgo** [comment]
Reverted the patch to modernizer 3.11.7 as it breaks the site. Needs more research.

**Comment by dvenckusuchgo** [comment]
I restricted the modernizr options & features to only the settings as existed in the original Drupal 8 core build of modernizr.  This results in a much smaller js lib and none of the previous problems the original build seemed to trigger.  Will attempt to patch Sandbox after hours in the next day or so.
