### ISSUE TITLE
Feature: Google Analytics and Tag Manager

### ISSUE THREAD

**Issue by dvenckusuchgo** [CBIIT/ccdhwebportal#6]
Complete setup/configuration of google-analytics (GA) and google tag manager (GTM).  Targeting version GA v4

**Comment by dvenckusuchgo** [comment]
Google analytics will continue reporting using the old version.  The Google Tag Manager version will not show data until GTM is deployed on the production site.
At this point, GTM deploys a single container for all tags on the site.  This can be re-evaluated at a later time if separate containers are needed for production vs local

**Comment by bfurner** [comment]
@dvenckusuchgo with this setup will we be able to separate traffic coming from the different tiers?

**Comment by dvenckusuchgo** [comment]
There is the capability to setup environments in GTM, but it requires further investigation.

**Comment by dvenckusuchgo** [comment]
Added view filtering to the original google analytics property.
Adding environment settings to GTM which requires we use config_split + config_filter (#14).
